### ISSUE TITLE
Resumen de tema: 0. Metodología Scrum - SOFTWARE

### ISSUE THREAD

**Issue by FranGemo1** [FranGemo1/Proyecto-programador-ispc-2022#16]

**Comment by Camigenti** [comment]
**Software:**
Son los programas, documentos asociados y la configuración de datos que se necesita para que esos programas funcionen correctamente
Cuando hablamos de documentacion nos referimos:
•	La organización del sistema
•	Documentos para el usuario con la explicación de como utilizarlos
•	Sitios web para la descarga de las actualizaciones del producto
Software (IEE): Es la parte de un sistema que se codifica para ejecutarse en una computadora .
_Características:_
•	Es tangible
•	Tiene alto desarrollo intelectual
•	Su proceso de desarrollo es humano intensivo
•	Puede ser potencialmente modificado de forma permanente
•	El software no se manufactura, se desarrolla
•	No se desgasta
•	Gran parte se construye a medida (Pressman)
**Desarrollo del Software:**
Estimar- Planificar- Diseñar- Controlar configuración- Recolectar requerimientos- Desarrollar software- Programar- Revisar técnicamente- Probar- Monitorear y controlar
Es un proceso que automatiza herramientas adaptándose a un proyecto, el cual requiere de la incorporación de personas obteniendo como resultado el Producto. 

**Procesos para el desarrollo de software:**
Define el conjunto completo de actividades necesarias para transformar los requerimientos del usuario en producto.
Existen distintos tipos de modelos de desarrollo:
•	Definidos o secuenciales
•	Empiricos
•	Modelo cascada: modelo lineal secuencial o ciclo de vida
**Hablaremos un poco mas sobre el modelo cascada o ciclo de vida:**
Es el conjunto de fases o procesos por las que pasa un software desde el inicio de su desarrollo hasta que se retira del servicio cuando finaliza su uso.
Estas fases están estandarizadas, hay un marco de referencia con los procesos, actividades y tareas involucradas en el desarrollo, explotación y mantenimiento del producto.
Se utilizan Curvas de fallos para la medición del funcionamiento del software desarrollado
**Agile**
A diferencia de las metodologías mencionadas anteriormente, Agile no es una de ellas, es mas bien una ideología con principios que guían el desarrollo de un producto.
Trabaja en la adaptación y mejora continua, no hay productos finales, si no productos que evolucionan y mejoran.
_Manifiesto Agile (valores)_
•	Valorar a los individuos por encima de los procesos
•	El software funciona por encima de la documentación exhaustiva
•	La colaboración del cliente por encima de la negociación contractual
•	La respuesta al cambio por encima del seguimiento de un plan
_Principios Agile:_
•	Colaboración estrecha con el cliente
•	Predisposición y respuesta al cambio
•	Desarrollo incremental con entregas frecuentes de funcionalidad
•	Comunicación verbal directa
•	Simplicidad, solo los artefactos necesarios
•	Motivación, compromiso y responsabilidad del equipo por la auto-gestión auto-organización.
•	Satisfacer al cliente mediante la entrega temprana y continua del software con valor
•	Aceptamos que los requisitos cambien, incluso en etapas tardías del desarrollo
•	Entregamos software funcional frecuentemente, entre dos semanas y dos meses, con preferencia el periodo de tiempo mas corto posible. 
•	Los responsables de negocio y desarrolladores trabajamos juntos de forma cotidiana durante todo el proyecto.
•	Los proyectos se desarrollan en torno a individuos motivados
•	El método mas eficiente y efectivo de comunicar información al equipo de desarrollo y entre sus miembros es la conversación cara a cara.
•	El software funcionando es la medida principal de progreso
•	Los procesos Agiles promueven el desarrollo sostenible. Los promotores, desarrolladores y usuarios debemos ser capaces de mantener un ritmo constante de forma indefinida
•	La atención continua a la excelencia técnica y a buen diseño mejora la agilidad.
•	La simplicidad o el arte de maximizar la cantidad de trabajo no realizado, es esencial.
•	Las mejores arquitecturas, requisitos y diseños emergen de equipos auto-organizados.
•	A intervalos regulares el equipo reflexiona sobre como ser mas efectivo para a continuación ajustar y perfeccionar su comportamiento en consecuencia.
