### ISSUE TITLE
Resumen de tema: 4. Sistemas Gestores de Bases de Datos 

### ISSUE THREAD

**Issue by FranGemo1** [FranGemo1/Proyecto-programador-ispc-2022#2]
Realizar un resumen del material de la plataforma del Ispc, materia programador de los SGBD.

**Comment by dariogiana** [comment]
Completo el resumen de 4. Sistemas Gestores de Bases de Datos parte "a" pag 1 a 9 del PDF, correspondiente a esta Issue.
