### ISSUE TITLE
Resumen de tema:  2. Historia y evolución de los SGBD II

### ISSUE THREAD

**Issue by FranGemo1** [FranGemo1/Proyecto-programador-ispc-2022#5]
Realizar resumen del material de estudio del Ispc: Materia programador, Historia y evolución de los SGBD.

**Comment by Gerx2690** [comment]
### Historia y evolución de los SGBD II

**Década de los 80 – SGBD Relacionales:** 
En los ’80 se desarrolló **SQL** (structure query lenguage), **un lenguaje que permite consultar y hacer modificaciones** (dentro de una base de datos) de forma relativamente sencilla. 
Permitía analizar gran cantidad de datos y especificar varios tipos de operaciones con una misma información. 
Imponiéndose frente a los SGBD (sistemas gestores de base de datos) anteriores como IMS de IBM, IDS de Bull y DMS de Univac, entre otros, que eran totalmente centralizados y demasiado complejos e inflexibles, cuya utilización requería un personal muy cualificado. 
SQL comenzó a ser el modelo estándar de las industrias con su base de datos bajo un sistema de tablas (filas y columnas) ya que su nivel de programación era sencillo y su nivel relativamente bajo.  El sistema de bases de datos relacional fue un éxito comercial y como también lo fue la venta de ordenadores estimulando el mercado de las BD. 
El dominio de Oracle en el mercado fue casi total hasta la aparición de SQL Server de Microsoft. Posteriormente durante los ’90 fueron apareciendo nuevos sistemas de SGBD Relacionales como PostgreSQL, My SQL y Firebird gestando así las BD orientadas a objetos. 

Década de los 90: Distribución, C/S y 4GL:
La necesidad de tener una visión global de la empresa y de interrelacionar diferentes aplicaciones que utilizan BD diferentes, junto con la facilidad que dan las redes para la intercomunicación entre ordenadores, ha conducido a los SGBD actuales, que permiten que un programa pueda trabajar con diferentes BD como si se tratase de una sola. **Eso se lo conoce como base de datos distribuida.**
La tecnología que se utiliza habitualmente para distribuir datos es la que se conoce como arquitectura cliente/servidor (C/S). Todos los SGBD relacionales del mercado han sido adaptados a éste entorno.
La idea del C/S es sencilla. Dos procesos diferentes que se ejecutan en un mismo sistema o en sistemas separados, actúan de forma que uno tiene el papel de cliente o peticionando un servicio y el otro el de servidor o proveedor del servicio.




Continuará…

**Comment by Karen-Pigni** [comment]
Ger ¿podrías agregar esto al readme?
