### ISSUE TITLE
Resumen de tema: 4. Sistemas Gestores de Bases de Datos 2

### ISSUE THREAD

**Issue by FranGemo1** [FranGemo1/Proyecto-programador-ispc-2022#7]
Realizar resumen del material de estudio del Ispc: Materia programador, Sistemas Gestores de Bases de Datos 2.

**Comment by dariogiana** [comment]
@Karen-Pigni  estuve ojeando el contenido de 4. Sistemas Gestores de Bases de Datos, el cual incluye un PDF de 19 páginas con bastante contenido distribuido de forma pareja. Propongo que uno de nosotros resuma de la pagina 1 a la 9, y el otro de la 10 a la 19. Como yo propongo la división, si estas de acuerdo, vos elegí si querés la primera o la segunda parte.

link del material:

https://acceso.ispc.edu.ar/pluginfile.php/51710/mod_book/chapter/1779/03%20-%20Sistemas%20Gestores%20de%20Bases%20de%20Datos%20-%20Estructura%20interna.pdf

**Comment by Karen-Pigni** [comment]
Perfecto @dariogiana, revisé el material, concuerdo en la división. Si querés yo hago desde la pagina 10 a las 19 (segunda parte) y ante cualquier duda, nos vamos consultando!

**Comment by dariogiana** [comment]
perfecto! vamos así, entonces. Yo agarro las 9 primeras y nos vamos consultando cualquier inquietud.
